fos_oauth_server:
  db_driver: orm
  client_class: App\Entity\Auth\Client
  access_token_class: App\Entity\Auth\AccessToken
  refresh_token_class: App\Entity\Auth\RefreshToken
  auth_code_class: App\Entity\Auth\AuthCode