gesdinet_jwt_refresh_token:
    ttl: 2592000 # 30 days. If no connexion during this time, the user will need to log in again from the mobile app.
    ttl_update: true # Each time the token is refreshed, the ttl is renewed
    user_provider: security.user.provider.concrete.app_user_provider