vich_uploader:
    db_driver: orm

    mappings:
        students_photos:
            upload_destination: '%kernel.project_dir%/var/files/students'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


        excuses_photos:
            upload_destination: '%kernel.project_dir%/var/files/proofs'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

