vich_uploader:
    db_driver: orm

    mappings:
        students_photos:
            uri_prefix: /students/photos
            upload_destination: '%kernel.project_dir%/public/students/photos'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
