api_controllers:
    resource: ../../src/Controller/Api/
    type: annotation
    name_prefix: api_
    prefix: /api

controllers:
    resource: ../../src/Controller/*.php
    type: annotation

security_controller:
    resource: ../../src/Controller/SecurityController.php
    type: annotation